---
abstract: 'Typo Corrector for Korean language in using English'
author:
  - iamseeker,
build_requires:
  ExtUtils::MakeMaker: 6.62
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-KO-TypoCorrector
no_index:
  directory:
    - inc
    - t
requires:
  Exporter: 0
  Filter::Util::Call: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/JEEN/p5-Lingua-KO-TypoCorrector.git
version: 0.03
